mysql:
  host: 127.0.0.1
  port: 3306
  config: ""
  db: xl_db
  user: root
  password: ""
  log_level: dev
logger:
  level: warning
  prefix: '[xl]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: debug
site_info:
  create_at: "2023-02-12"
  bei_an: 沪ICP
  title: xl的个人博客
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/qq.png
  version: 6.0.2
  email: 1414104227@qq.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: 小老鼠吃灯油
  job: 后端开发
  addr: 上海
  slogan: xl博客
  slogan_en: XLBLOG
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao/
qq:
  app_id: ""
  key: ""
  redirect: ""
qi_niu:
  access_key: UMM-xx-FdRIf-xx
  secret_key: ""
  bucket: chichichi
  cdn: xx://xx.xx.com/
  zone: xx
  size: 5
email:
  host: ""
  port: 123456
  user: ""
  password: ""
  default_from_email: ""
  use_ssl: false
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
